// <auto-generated />
#nullable enable

using global::System.Diagnostics.CodeAnalysis;
using global::System.Diagnostics;
using global::System.Runtime.CompilerServices;

namespace Microsoft.PowerPlatform.TypedStrings.Generator
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.PowerPlatform.TypedStrings.Generator", "1.0.0.0")]
    [DebuggerDisplay("{GetDebuggerDisplay}")]
    [SuppressMessage("Design", "CA1036:Override methods on comparable types", Justification = "TODO")] // Remove this suppression and implement using latest recommended performant implementation.
    public partial record TypedStringTestCustomIsValid : global::Microsoft.PowerPlatform.TypedStrings.ITypedString<TypedStringTestCustomIsValid>
    {
        public TypedStringTestCustomIsValid(string value)
        {
            Value = ValidateArgument(value);
        }

        public string Value { get; }

        public static implicit operator string(TypedStringTestCustomIsValid name) => name.Value;

        

        public override string ToString() => Value;

        public int CompareTo(TypedStringTestCustomIsValid? other) => Value.CompareTo(other?.Value);

        private string GetDebuggerDisplay => $"{nameof(TypedStringTestCustomIsValid)} {{ Value = {Value} }}";

        private static string ValidateArgument([NotNull] string? value, [CallerArgumentExpression(nameof(value))] string? argumentName = null)
        {
            if (!TryValidate(value, out var validated))
            {
                throw new ArgumentException($"Invalid value for a {nameof(TypedStringTestCustomIsValid)}.", argumentName);
            }
            return validated;
        }

        /// <summary>
        /// Validates the input value and returns a validated string.
        /// </summary>
        private static bool TryValidate([NotNullWhen(true)] string? value, [NotNullWhen(true)] out string? validated)
        {
            if (IsValid(value))
            {
                global::System.Diagnostics.Debug.Assert(value != null); // Verify `IsValid` is "well behaved".

                validated = value;
                return true;
            }

            validated = null;
            return false;
        }

        public static TypedStringTestCustomIsValid Parse(string value, IFormatProvider? provider)
        {
            _ = value ?? throw new ArgumentNullException(nameof(value));

            if (!TryParse(value, provider, out var parsed))
            {
                throw new FormatException($"Invalid string format for a TypedStringTestCustomIsValid.");
            }

            return parsed;
        }

        public static bool TryParse(string? value, IFormatProvider? provider, [NotNullWhen(true)] out TypedStringTestCustomIsValid? result)
        {
            if (!TryValidate(value, out var validated))
            {
                result = default;
                return false;
            }

            result = new(value);
            return true;
        }
    }
}