// <auto-generated />
#nullable enable

namespace Microsoft.PowerPlatform.TypedStrings.Generator
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.PowerPlatform.TypedStrings.Generator", "1.0.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class TypedStringAttribute : global::System.Attribute
    {
    }
}