// <auto-generated />
#nullable enable

using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::Microsoft.PowerPlatform.TypedStrings;

namespace Microsoft.PowerPlatform.TypedStrings.Generator;

public partial record TypedStringTestDefaultIsValid : ITypedString<TypedStringTestDefaultIsValid>
{
    public TypedStringTestDefaultIsValid(string value)
    {
        Value = ValidateArgument(value);
    }

    public string Value { get; }

    public static implicit operator string(TypedStringTestDefaultIsValid name) => name.Value;

    // Default implementation of IsValid will simply verify the value is not null.
// You may implement your own method as long as it's static, and has the same argument signature.
// You should be able to override the access modifier as needed for your usage.
private static bool IsValid([NotNullWhen(true)] string? value) => value != null;

    public override string ToString() => Value;

    private static string ValidateArgument([NotNull] string? value, [CallerArgumentExpression(nameof(value))] string? argumentName = null)
    {
        if (!TryValidate(value, out var validated))
        {
            throw new ArgumentException($"Invalid value for a {nameof(TypedStringTestDefaultIsValid)}.", argumentName);
        }
        return validated;
    }

    /// <summary>
    /// Validates the input value and returns a validated string.
    /// </summary>
    private static bool TryValidate([NotNullWhen(true)] string? value, [NotNullWhen(true)] out string? validated)
    {
        if (IsValid(value))
        {
            global::System.Diagnostics.Debug.Assert(value != null); // Verify `IsValid` is "well behaved".

            validated = value;
            return true;
        }

        validated = null;
        return false;
    }

    static TypedStringTestDefaultIsValid IParsable<TypedStringTestDefaultIsValid>.Parse(string s, IFormatProvider? provider)
    {
        // TODO
        throw new NotImplementedException();
    }

    static bool IParsable<TypedStringTestDefaultIsValid>.TryParse(string? s, IFormatProvider? provider, out TypedStringTestDefaultIsValid result)
    {
        // TODO
        throw new NotImplementedException();
    }
}